GET http://localhost:3000/query
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "customer_first_name": "selena"
          }
        },
        {
          "match": {
            "customer_last_name": "Carpenter"
          }
        }
      ]
    }
  }
}
