@port = 3000
###
GET http://localhost:{{port}}/query
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "customer_first_name": "selena"
          }
        },
        {
          "match": {
            "customer_last_name": "Carpenter"
          }
        }
      ]
    }
  }
}


###
GET http://localhost:{{port}}/query
Content-Type: application/json

{
  "query": {
    "match": {
      "customer_last_name": "Carpenter"
    }
  }
}

###
GET http://localhost:{{port}}/health_check